name: Build & Check Pull Request
on:
  pull_request:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install and Build 🔧
        run: |
          npm install
          npm run build

